FROM python:3.11

WORKDIR /app

RUN pip install uv

COPY requirements.txt .
RUN uv pip install --system -r requirements.txt

COPY train.ipynb /app/

COPY models/ /app/models/

COPY models_performance/ /app/models_performance/

COPY datasets/ /app/datasets/


EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]